# docker-compose.yml
name: tgsm-bot
services:
  app:
    build: .
    env_file: 
      - .env
    environment:
      - SERVER_ADDR=0.0.0.0
      - SERVER_PORT=${SERVER_PORT:-80}
    volumes:
      - ./:/app  
      - ${STORAGE_PATH:-./db}:/db
      - ${LOG_PATH:-./logs}:/logs 
    networks:
      host-bridge:
        ipv4_address: 172.30.0.10  # Фиксированный IP
    restart: unless-stopped

networks:
  host-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
